version: '3.4'

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
      #- ./data:/data/db
    ports:
      - "27017:27017"

  todo.api:
    image: ${DOCKER_REGISTRY-}todoapi
    build:
      context: .
      dockerfile: Todo.API/Dockerfile
    ports:
      - 7000:80
    links:
      - mongo
